# Generated by Django 4.0 on 2021-12-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('bw', models.CharField(max_length=50)),
                ('nw', models.CharField(max_length=50)),
                ('pickups', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GuitarPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='uploads')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.color')),
            ],
        ),
    ]
